server:
  port: 14001
logging:
  level:
    root: INFO
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR
################### Spring DataSource Configuration ##########################
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///javaweb?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
  mvc:
    view:
      suffix: html
    static-path-pattern: /**
  servlet:
    multipart:
      enabled: true
#  resources:
#    static-locations: classpath:/static/
################### Mybatis DataSource Configuration ##########################
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.ky.jzk.model
  type-handlers-package: cn.kevin.ims.handler
################### Shiro DataSource Configuration ##########################
